In [1]:
import numpy as np

1.Write a NumPy program to get the numpy version

In [8]:
np.__version__ 

'1.19.5'

2. Write a NumPy program to  get help on the add function

In [ ]:
help(np.add)

3. Write a NumPy program to test whether none of the elements of a given array is zero

In [14]:
a = np.array([1,2,3,4,0])
np.all(a)

False

4. Write a NumPy program to test whether any of the elements of a given array is non-zero

In [15]:
np.any(a)

True

5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [19]:
a = np.array([1, 0, np.nan, np.inf])
np.isfinite(a)

array([ True,  True, False, False])

6. Write a NumPy program to test element-wise for positive or negative infinity. 

In [21]:
np.isposinf(a), np.isneginf(a)

(array([False, False, False,  True]), array([False, False, False, False]))

7. Write a NumPy program to test element-wise for NaN of a given array

In [22]:
np.isnan(a)

array([False, False,  True, False])

8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not

In [30]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
np.iscomplex(a), np.isreal(a), np.isscalar(a)

(array([ True, False, False, False, False,  True]),
 array([False,  True,  True,  True,  True, False]),
 False)

10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [36]:
x = np.array([3, 5])
y = np.array([2, 5])
x>y, x>=y, x<y

(array([ True, False]), array([ True,  True]), array([False, False]))

11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [39]:
np.equal(x,y)

array([False,  True])

12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array

In [46]:
a = np.array([1,7,13,105])
'%d bytes' % (a.size*a.itemsize)

'16 bytes'

13.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [47]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [50]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

14. Write a NumPy program to create an array of the integers from 30 to70

In [52]:
x = np.array(range(30,71))
x

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

15. Write a NumPy program to create an array of all the even integers from 30 to 70. 

In [54]:
x= np.array(range(30,71,2))
x

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

16. Write a NumPy program to create a 3x3 identity matrix.

In [56]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])