In [1]:
import numpy as np

17. Write a NumPy program to generate a random number between 0 and 1.

In [19]:
ran_num = np.random.normal(0,1,1)
ran_num

array([-1.64010178])

18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [29]:
ran_num = np.random.normal(0,1,15)
ran_num

array([-1.42930325, -0.09510493,  0.87378887, -0.58018221,  0.410268  ,
        1.52349343,  0.78627508, -0.28477591, -0.36054736, -2.58928676,
        0.74680631, -0.51271001,  1.02672892, -0.35981916,  1.45519205])

19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [32]:
vector = np.arange(15,56)
vector[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

20. Write a NumPy program to create a 3X4 array using and iterate over it.

In [36]:
arr = np.arange(12).reshape(3,4)
for x in np.nditer(arr):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [43]:
arr = np.linspace(5,50,num=10)
arr

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [45]:
v = np.array(range(0,21))
v[(v>=9) & (v<=15)]*-1

array([ -9, -10, -11, -12, -13, -14, -15])

23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [50]:
v = np.random.randint(0,11,5)
v

array([2, 7, 0, 0, 5])

24. Write a NumPy program to multiply the values of two given vectors. 

In [54]:
v1 = np.array([1,2,3,4])
v2 = np.random.randint(5,10,4)
v1*v2

array([ 6, 18, 24, 28])

25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [59]:
m = np.arange(10,22).reshape(3,4)
m

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

26. Write a NumPy program to find the number of rows and columns of a given matrix.

In [64]:
m.shape

(3, 4)

27. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0. 

In [65]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

28. Write a NumPy program to create a 5x5 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [73]:
m = np.ones((5,5))
m[1:-1,1:-1]=0
m

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5

In [82]:
m = np.zeros((5,5))
m = np.diag([1,2,3,4,5])
m

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

30. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal

In [108]:
m=np.zeros((4,4))
m[::2,1::2]=1
m[1::2,::2]=1
m

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

31. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [115]:
m = np.random.random((3,3,3))
m

array([[[0.13719872, 0.5429809 , 0.91986773],
        [0.11926331, 0.18742204, 0.37240528],
        [0.48712247, 0.53890419, 0.39196834]],

       [[0.34592591, 0.55907493, 0.51856078],
        [0.54005754, 0.58266182, 0.31745283],
        [0.76366364, 0.88000549, 0.09870487]],

       [[0.0141245 , 0.55033567, 0.97318083],
        [0.13210656, 0.50188483, 0.94766978],
        [0.2861487 , 0.08766126, 0.27272406]]])

32. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [120]:
arr1 = np.arange(12).reshape(3,4)
arr1.sum(axis=1),arr1.sum(axis=0)

(array([ 6, 22, 38]), array([12, 15, 18, 21]))

33. Write a NumPy program to compute the inner product of two given vectors.

In [121]:
arr2 = np.arange(12).reshape(4,3)
np.dot(arr1,arr2)

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])